### ISSUE TITLE
crashes on injecting

### ISSUE THREAD

**Issue by rolexlinux** [ArnoldasMk/Kali#14]
[mong@MatrixPower Kali]$ ./Kali -l
[sudo] password for root: 
loading...
Injecting Build ID: libQt5WebSockets.so
2
-- csgo crashes then it says
Successfully injected!

**Comment by rolexlinux** [comment]
also I'm on arch linux and this seems to happen for any cheat

**Comment by ArnoldasMk** [comment]
what gdb version are you using ?

**Comment by rolexlinux** [comment]
gdb --version reported
GNU gdb (GDB) 11.1

**Comment by ArnoldasMk** [comment]
https://github.com/LWSS/Fuzion/issues/621#issuecomment-777815272 try this

**Comment by rolexlinux** [comment]
> [LWSS/Fuzion#621 (comment)](https://github.com/LWSS/Fuzion/issues/621#issuecomment-777815272) try this

didn't work for me still crashing even when using precompiled gdb

[mong@MatrixPower Kali]$ gdb --version
GNU gdb (GDB) 9.1
[mong@MatrixPower Kali]$ ./Kali -l
loading...
Injecting Build ID: libQt5WebSockets.so
2
-- csgo freezes and after crash reports successful injection
Successfully injected!

**Comment by ArnoldasMk** [comment]
Okay, what distro are you using ?

**Comment by ArnoldasMk** [comment]
Also, update if you haven't yet

**Comment by rolexlinux** [comment]
> Okay, what distro are you using ?

arch

**Comment by rolexlinux** [comment]
> Also, update if you haven't yet

i did ./Kali -u which reported
[mong@MatrixPower Kali]$ ./Kali -u
[sudo] password for root: 
Already up to date.
-- then recompiles

but even after recompiling still crashing

idk if its my mesa version
[mong@MatrixPower Kali]$ glxinfo | grep "OpenGL version"
--reports
OpenGL version string: 4.6 (Compatibility Profile) Mesa 21.2.5

should i try building in debug mode?

**Comment by ArnoldasMk** [comment]
Try
```
git pull
```
And if it says "Already Up to date"  then my guess is something with kernel versions, people said that they have issues injecting while being on arch. I tried running on VM manjaro, for me it worked without issues.

**Comment by ArnoldasMk** [comment]
Also try this one too, https://github.com/LWSS/Fuzion/issues/651#issuecomment-894206146

**Comment by rolexlinux** [comment]
> Try
> 
> ```
> git pull
> ```
> 
[mong@MatrixPower Kali]$ git pull
Already up to date.

> Also please tell me your kernel version.
[mong@MatrixPower Kali]$ uname -r
5.15.4-arch1-1

> Also try this one too, [LWSS/Fuzion#651 (comment)](https://github.com/LWSS/Fuzion/issues/651#issuecomment-894206146) Place it In Kali folder.

ok so i did this cmd

```
[mong@MatrixPower Kali]$ wget https://nullworks.gitlab.io/cathook/cathook/gdb -O gdb.bin && sudo chmod +x ./gdb.bin && sed -i -- 's/sudo gdb/sudo .\/gdb.bin/g' ./Kali
```

which did its things no errors
then i tried injecting same crash

**Comment by ArnoldasMk** [comment]
Hmmm, what about other cheats ? Have you tried gamesneeze?

**Comment by rolexlinux** [comment]
> Hmmm, what about other cheats ? Have you tried gamesneeze?

yes but I did this
```
[mong@MatrixPower gamesneeze]$ ./toolbox.sh -l
Loading cheat...
Successfully injected!
```
but the cheat doesn't really inject into csgo like no menu

**Comment by ArnoldasMk** [comment]
> [mong@MatrixPower Kali]$ uname -r
5.15.4-arch1-1

A user in discord said that he also can't inject, and he's using almost the same version of kernel you're using. He's using 5.15.4-zen1-1-zen. I tested Kali on Vm, Vm is running on 5.13.19-arch-2 and GDB version 11.1 and it's running perfectly, can you try downgrading kernel ?

**Comment by rolexlinux** [comment]
> Have you tried downgrading kernel ?

[mong@MatrixPower ~]$ uname -r
5.13.13-arch1-1

This actually has fixed the error and it injected im gonna test gdb 11

**Comment by rolexlinux** [comment]
yup seemed to be the kernel

**Comment by rolexlinux** [comment]
Downloading this with pacman -U and rebooting fixed it
https://archive.archlinux.org/packages/l/linux/linux-5.13.13.arch1-1-x86_64.pkg.tar.zst

**Comment by ArnoldasMk** [comment]
Good
