### ISSUE TITLE
Loading causes the game to close

### ISSUE THREAD

**Issue by Comm4nd0** [ArnoldasMk/Kali#17]
While in the main menu, when loading (./kali -l ) cs:go closes instantly.

**Comment by ArnoldasMk** [comment]
Yeah, I experience the same issue, have you tried other cheats ? Do they work tho ?

**Comment by Comm4nd0** [comment]
No, not tried anything else.

**Comment by ArnoldasMk** [comment]
Well I tried Fuzion, It crashes, so I guess I will wait for LWSS to fix it and we I will just paste the fix.

**Comment by Comm4nd0** [comment]
What's LWSS? I've tried running steam via a terminal and generated the bug, it just says:
[1]  + 9307 suspended (signal)  steam

**Comment by ArnoldasMk** [comment]
> What's LWSS?
https://github.com/LWSS/Fuzion, he's the dev of Fuzion

**Comment by Comm4nd0** [comment]
Oh i see! yeah i've just cloned Fusion. are you doing anything with Kali to make it less detectable?

**Comment by ArnoldasMk** [comment]
My plans are: Menu rework, then cheat cleanup to make it as clean as possible, because it's a fork of fork of fork...

**Comment by ArnoldasMk** [comment]
https://www.youtube.com/watch?v=W6ZhxO0lARM&ab_channel=CS%3AGOSDKTutorials, this is the fix, I found this in MissedIT discord
