### ISSUE TITLE
Latest CSGO update broke the cheat

### ISSUE THREAD

**Issue by DacianKing** [ArnoldasMk/Kali#18]
Running Kali on the latest CSGO update freezes the game (many cheats are currently having this issue). Offsets and patterns seem to have changed.

**Comment by DacianKing** [comment]
Also wondering do you have a Discord server for this cheat? Quite a lot of good features and would be interested in helping out in development.

**Comment by DacianKing** [comment]
Just tried the fix on the other closed issue you have posted (youtube link) and it does indeed work. However it might be good to add this to the readme just so people can fix it without posting an issue like me. For anyone else needing the video to fix this issue here is the link: https://www.youtube.com/watch?v=W6ZhxO0lARM

**Comment by ArnoldasMk** [comment]
> Also wondering do you have a Discord server for this cheat? Quite a lot of good features and would be interested in helping out in development.

I am planning to create one, when I will push a menu update.

> Just tried the fix on the other closed issue you have posted (youtube link) and it does indeed work.

So did you fix the issue you mentioned in the first comment? 

> However it might be good to add this to the readme just so people can fix it without posting an issue like me. For anyone else needing the video to fix this issue here is the link: [youtube.com/watch?v=W6ZhxO0lARM](https://www.youtube.com/watch?v=W6ZhxO0lARM)

I pinned the issue with a fix.
