### ISSUE TITLE
CSGO crashes when injecting, Ubuntu 20.04

### ISSUE THREAD

**Issue by zaquinn** [ArnoldasMk/Kali#19]
Hi, I did everything right but when I try to inject the cheat CSGO crashes, in terminal showed that the cheat was sucessfully injected. Im on Ubuntu 20.04, anyone knows how to fix it?

**Comment by DacianKing** [comment]
Please refer to this video https://www.youtube.com/watch?v=W6ZhxO0lARM . I did this and it worked for me

**Comment by ArnoldasMk** [comment]
> Hi, I did everything right but when I try to inject the cheat CSGO crashes, in terminal showed that the cheat was sucessfully injected. Im on Ubuntu 20.04, anyone knows how to fix it?

Does it work now after the update ?

**Comment by zaquinn** [comment]
ye, working fine now, ty
