### ISSUE TITLE
[Question] fonts

### ISSUE THREAD

**Issue by DrunkenBlyatHvH** [ArnoldasMk/Kali#3]
Do i need to copy the folder /Kali/fonts or do i need to copy the files form the folder /Kali/fonts into /csgo/panorama/fonts/ ?

**Comment by ArnoldasMk** [comment]
If you're talking about weapon esp font, you need to copy astriumwep.ttf from /Kali/fonts to (CSGODIR)/csgo/panorama/fonts/

**Comment by DrunkenBlyatHvH** [comment]
ah ok

**Comment by DrunkenBlyatHvH** [comment]
thx
