### ISSUE TITLE
Disconnects the game every 5 seconds or so.

### ISSUE THREAD

**Issue by uni-901** [ArnoldasMk/Kali#31]
Without injecting the script, game does not disconnect and cause lag but as soon as you inject whether you enable any feature or not, it starts to disconnect the game every 5-10 seconds. I am not good at this but i think the libqt web engine is causing this issue??

hope to get an update.  thanks for this awesome script.

**Comment by ArnoldasMk** [comment]
sorry for late response, I stopped working on this cheat. Are you using flatpak steam ?

**Comment by ArnoldasMk** [comment]
I will close it now, no response.
