### ISSUE TITLE
Activating Visuals crushes the game

### ISSUE THREAD

**Issue by sicr0** [ArnoldasMk/Kali#36]
The moment I activate visuals the game crushes

**Comment by RuiSupremacy** [comment]
you fixed it yet?

**Comment by sicr0** [comment]
@RuiSupremacy I'm not a developer so I couldn't fix it. I also got the same problem on `Fuzion` which is a cheat that this program forkes on. [This](https://github.com/LWSS/Fuzion/issues/683) is the issue I opened there

**Comment by s-b-repo** [comment]
i think should be closed it is fixed isnt it

**Comment by ignamartinoli** [comment]
Tonight (like 6 hours) I'm going to sit down and try it. If it's fixed I'm closing this

**Comment by ignamartinoli** [comment]
Well, I don't have permission to close issues, but I'm gonna report back if it's fixed or not so that whoever has the access can close this

**Comment by ArnoldasMk** [comment]
yeah, please tell me if it's working, Thanks.

**Comment by sicr0** [comment]
It's fixed! Thanks!
