### ISSUE TITLE
Dumb Question

### ISSUE THREAD

**Issue by arrayffs** [ArnoldasMk/Kali#37]
I have a question, im trying to get into Linux game hacking & modding, and i was curious, is just changing the .so file name everything needed to do for bypassing VAC?

**Comment by ArnoldasMk** [comment]
Hello, well in theory yes, you can learn more about VAC [here](https://lwss.github.io/State-Of-Vac-linux-2020/) by LWSS.

**Comment by ArnoldasMk** [comment]
I think I can close this now.
