### ISSUE TITLE
Graphics slowdown when injecting hack

### ISSUE THREAD

**Issue by ericbarreto21** [ArnoldasMk/Kali#38]
Hello,

After injecting the hack, I always experience a graphical slowdown even with fps above 100 and ping below 10ms.

After disabling the chams function by commenting out the line of code:
Chams::DrawModelExecute(thisptr, context, state, pInfo, pCustomBoneToWorld);

I had an improvement in this slowness, but it didn't solve 100% of the problem.

**Comment by ArnoldasMk** [comment]
Duplicate.
