### ISSUE TITLE
game crashes when you press page down under certain circumstances

### ISSUE THREAD

**Issue by cstles** [ArnoldasMk/Kali#4]
self explanatory
also happens on vanilla fuzion

**Comment by cstles** [comment]
game also crashes when you enable auto shoot on the dualies in rage

**Comment by ArnoldasMk** [comment]
Okey, I see now. Well I'm in the middle of menu rework, maybe this will fix, because I think it is because of the shitty menu code.

**Comment by ArnoldasMk** [comment]
Also, Fuzion menu is almost the same as EyeHook, soo....

**Comment by ArnoldasMk** [comment]
Ok I tested autoshoot on the new menu, and it crashes......
