### ISSUE TITLE
Noob question

### ISSUE THREAD

**Issue by ilievi187** [ArnoldasMk/Kali#41]
Hello 
I have been playing CS:GO for years , I've never used a cheats or any kind of external software.
Yesterday i was very tired and sad and i was losing couple of matches against people with software, so i've cloned this cheat and i insterted it when i was in a match. CS:GO crashed than i unload it , and i've reconnect. Am i gonna get VAC ban for inserting the cheat when i was in server ? Are they gonna notice ?

**Comment by ArnoldasMk** [comment]
Hello, no, don't worry, vac on linux isn't the best, I would be surprised if you get VAC banned.
