### ISSUE TITLE
help pls!

### ISSUE THREAD

**Issue by Dallleworthy** [ArnoldasMk/Kali#44]

**Comment by idanoo** [comment]
What happens when you press the shortcuts in the README?

`Now that Kali has been injected into the game, press Insert on your keyboard to open the hack menu (ALT+I if you are using a laptop).`

**Comment by ArnoldasMk** [comment]
Hello, are you using flatpak steam?

**Comment by sourcelocation** [comment]
Same issue @ArnoldasMk, using Flatpak version

**Comment by ArnoldasMk** [comment]
Yeah, don't use flatpak then.

**Comment by sourcelocation** [comment]
Switching from Flatpak helped, thank you @ArnoldasMk !
