### ISSUE TITLE
Crash when attempting to load UI

### ISSUE THREAD

**Issue by idanoo** [ArnoldasMk/Kali#45]
After pulling the latest commit (https://github.com/ArnoldasMk/Kali/commit/4a486e294f9e2d90ceaf4ab91ca92bb4ad9f5724), pressing ALT+I crashes CSGO.

I attempted to build the debug version and run ./debug but got nothing useful from GDB. Probably just don't know what I'm doing. 

I have rolled back to the previous commit hash and it's working again for now (c12410b16f6865c40f0c6a288cf591956a7376b1)

**Comment by idanoo** [comment]
Actually it seems to be crashing on that hash as well.. Will dig a bit more and reopen if I can find anything specific

**Comment by idanoo** [comment]
Yep. It's a me issue. 

Probably needed to run `./Kali -u` but I just did a git update and didn't run clean. :upside_down_face:

**Comment by ArnoldasMk** [comment]
Hello, so You fixed it right ?
