### ISSUE TITLE
Keep getting VAC banned

### ISSUE THREAD

**Issue by ignamartinoli** [ArnoldasMk/Kali#57]
After two or three days playing I consistently get VAC banned.

Enabled:
- Triggerbot (actually use it very rarely)
- In-game Radar
- No Flash: 255
- Grenade Prediction
- Bunny Hop
- Sniper Crosshair
- Fast Walk
- AWP Quick Switch

**Comment by gingerchicken** [comment]
Is it a VAC or just overwatch?

**Comment by ignamartinoli** [comment]
@gingerchicken It says VAC banned. 
I use only radar and triggerbot sometimes to avoid making it obvious

**Comment by Blu3cr0ss** [comment]
Kali is bad for legit imho use gamesneeze instead

**Comment by ignamartinoli** [comment]
@ArnoldasMk hi, sorry for the inconvenience.

Could you please delete this issue?
I stopped using cheats and I'm quite ashamed of having used it
