### ISSUE TITLE
No ./build or ./load files :)

### ISSUE THREAD

**Issue by tar420** [ArnoldasMk/Kali#8]
Forgot to add these to the new update with cmake i guess. 
Some people can't do anything without following your instructions so dropping those files would be highly appreciated!

**Comment by ArnoldasMk** [comment]
Oh yeah sorry I forgot to update ReadMe, thanks!

**Comment by ArnoldasMk** [comment]
Use ./Kali -l to load and ./Kali -b to build, i'm working on it right now

**Comment by ArnoldasMk** [comment]
Fixed!
