### ISSUE TITLE
New update for operating riptide completely breaks the cheat.

### ISSUE THREAD

**Issue by AdverseMiller** [ArnoldasMk/Kali#9]
The newly released operation riptide will cause the cheat to crash when using it in game. I've tried many different configs and even just having the cheat injected with no config selected will still cause the cheat to crash. I've noticed this to happen with multiple other AImtux based cheats.

**Comment by Altonos** [comment]
https://github.com/KittenPopo

**Comment by Altonos** [comment]
This is normal, Valve has changed the sig.
From [40 0F B6 FF 55 ] to [55 48 89 E5 41 56 41 55 41 54 53 48 83 EC 30 66 0F D6 45 D0]

**Comment by ArnoldasMk** [comment]
Okay I fixed crash, but now visuals -> enemy -> chams crash the game, so yeah!

**Comment by ArnoldasMk** [comment]
Fixed in 1eb2394
